# ~/.config/hypr/conf/input.conf
device {
    name = input-remapper-kensington-expert-wireless-tb-mouse-forwarded
    sensitivity = 0.40
    accel_profile = flat   # removes acceleration curve
}

device {
    name = elan0672:00-04f3:3187-touchpad
    sensitivity = 0.40
    accel_profile = flat    # removes acceleration curve
    natural_scroll = true
}

