name: Check Nightly

on:
  issues:
    types: [opened, edited]
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-js: 20

      - name: Install Dependencies
        run: |
          cd scripts
          npm ci

      - name: Check Nightly
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./scripts/check-nightly/main.js')
            await script({github, context, core})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
